### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'grad_fn'

### ISSUE THREAD

**Issue by lzhaozi** [szagoruyko/pytorchviz#10]
My env is python2.7+pytorch0.3.1.
When I try this repo, I face the problem:
AttributeError: 'tuple' object has no attribute 'grad_fn'

Does anybody know why? 
Is it because the pytorch version is not supported?

**Comment by Germanunkol** [comment]
You're probably not feeding a tensor/variable into the make_dot function? Make sure the output from your network is a variable (or tensor), then call make_dot with this result.
