### ISSUE TITLE
how about an example that triggers fillcolor='orange' in dot.py?

### ISSUE THREAD

**Issue by mepster** [szagoruyko/pytorchviz#11]
In dot.py there is a case in which a node will be plotted with fillcolor='orange'. However, none of the example networks in examples.ipynb show orange boxes - only blue and gray. Under what conditions are you supposed to get orange boxes? Can you tweak one of the example networks to illustrate this?

I've been playing with the code in dot.py, but I haven't been able to define a network that produces orange boxes... I don't think "torch.is_tensor(var)" ever evaluates to true... at least in no network I could come up with. (However, "torch.is_tensor(var.variable)" does sometimes evaluate true.)

Thanks! (Very useful tool!)

**Comment by YoelShoshan** [comment]
There is a visualization example which seems to show those "orange nodes".

https://github.com/szagoruyko/functional-zoo/blob/master/resnet-18-export.ipynb

However, I think that autograd changes between pytorch 0.3 and 0.4 broke that path.

**Comment by YoelShoshan** [comment]
Ok, there's an official answer about this question:

https://discuss.pytorch.org/t/traversing-computation-graph-and-seeing-saved-tensors-problem-edited-hopefuly-clearer/20575

**Comment by szagoruyko** [comment]
right, not possible without internal changes to pytorch, closing.
