### ISSUE TITLE
Issue with Multiple Networks

### ISSUE THREAD

**Issue by ranamihir** [szagoruyko/pytorchviz#19]
Hi,

I have a model which is a combination of two networks -- one's output going as input to the next one. The issues I face are:
1. For `make_dot`, I need to have a dictionary of all named parameters, which in turn means the layer names of one network cannot be the same as that of the second one.
2. For `make_dot_from_trace`, it creates some graph (which is not right), and since I want to compute the graph for the entire model end-to-end, I pass in the last network in `torch.jit.get_trace_graph`, but then only picks up the name of the second network and populates that name everywhere.

Any solutions around this?

**Comment by szagoruyko** [comment]
see #21  how to merge dicts of parameters of several networks:
```
{**dict(model0.named_parameters()), **dict(model1.named_parameters())}
```
you need to make sure there is no name overlap between two models

**Comment by ranamihir** [comment]
Yes, that's what I figured -- I was wondering if there's a way around this, because it doesn't sound like a very clean solution.

**Comment by szagoruyko** [comment]
well the more pytorchy way would be to stick the two models into a class or Sequential and use that, I guess

**Comment by ranamihir** [comment]
Alright, I guess I'll do that. Thanks.
