### ISSUE TITLE
Must it be running in jupyter notebook? 

### ISSUE THREAD

**Issue by jxgu1016** [szagoruyko/pytorchviz#3]
Or any way to export the graph to image files?

**Comment by adrianjav** [comment]
You can do
```
output = model(input)
dot = make_dot(output, params=dict(model.named_parameters()))
dot.format = 'svg'
dot.render()
```
to export it as a svg file in your working directory.

And if you want to know more I recommend you checking [this](http://graphviz.readthedocs.io/en/stable/manual.html) out.

**Comment by kaushikacharya** [comment]
> And if you want to know more I recommend you checking [this](http://graphviz.readthedocs.io/en/stable/manual.html) out.

To understand why graph is rendered and displayed directly one can have a look at [Jupyter Notebook](https://graphviz.readthedocs.io/en/stable/manual.html#jupyter-notebooks) section of graphviz's manual.
