### ISSUE TITLE
make_dot without backward nodes?

### ISSUE THREAD

**Issue by zhangjing1997** [szagoruyko/pytorchviz#32]
For a huge or complicated network, directly drawing with backward nodes seems to be lengthy and jumbled. So I'm wondering does this package support drawing model graph without showing backward nodes (but only show forward layers/nodes)? 

Thanks for your attention.

**Comment by szagoruyko** [comment]
check make_dot_from_trace. in make_dot there is no notion of 'forward graph', the graph shown is backward graph needed to do backprop

**Comment by VCBE123** [comment]
So can i draw a forward graph?

**Comment by szagoruyko** [comment]
see above, there is no forward graph in pytorch, unless you do jit trace
