### ISSUE TITLE
Not every modal has a  grad_fn

### ISSUE THREAD

**Issue by AronWater** [szagoruyko/pytorchviz#43]
I personally think that sometimes self-defined modal might not have grad_fn, so maybe could consider this more general case.

`'NetworkCIFAR' object has no attribute 'grad_fn'`

**Comment by aitikgupta** [comment]
Quoting [this answer](https://stackoverflow.com/questions/52468956/how-do-i-visualize-a-net-in-pytorch):

> make_dot expects a variable (i.e., tensor with grad_fn), not the model itself.

Try this snippet:
```
out = net(dummy_input) #net is your NetworkCIFAR instance, while dummy_input is a tensor
make_dot(out)
```
Moreover, `grad_fn` is a tensor attribute, not of the model itself.

**Comment by xiejiachen** [comment]
> Quoting [this answer](https://stackoverflow.com/questions/52468956/how-do-i-visualize-a-net-in-pytorch):
> 
> > make_dot expects a variable (i.e., tensor with grad_fn), not the model itself.
> 
> Try this snippet:
> 
> ```
> out = net(dummy_input) #net is your NetworkCIFAR instance, while dummy_input is a tensor
> make_dot(out)
> ```
> 
> Moreover, `grad_fn` is a tensor attribute, not of the model itself.

It seems not work with minGPT https://github.com/karpathy/minGPT

**Comment by szagoruyko** [comment]
thanks @aitikgupta ! closing
