### ISSUE TITLE
Does not output any figure

### ISSUE THREAD

**Issue by shahabty** [szagoruyko/pytorchviz#5]
Hello, 
I was running a simple code that is provided in examples. However, nothing showed up on the screen.
Can anyone help me?

**Comment by adrianjav** [comment]
Have you tried it on a jupyter-notebook document? Afaik the example code does work in there but doesn't output anything in a regular script.
[In this issue](https://github.com/szagoruyko/pytorchviz/issues/3#issuecomment-373873219) I said how to export the image to a svg file and that code does work for regular scripts. You just have to play with the graphviz library
