### ISSUE TITLE
Inconsistent arrow directions for saved variables

### ISSUE THREAD

**Issue by Varal7** [szagoruyko/pytorchviz#61]
For saved variables created in a custom autograd function, the direction `SavedVariable` -> `Node` is used. 
(cf. https://github.com/szagoruyko/pytorchviz/blob/master/torchviz/dot.py#L141)

For the other ones, no direction is used (cf. https://github.com/szagoruyko/pytorchviz/blob/master/torchviz/dot.py#L110 and https://github.com/szagoruyko/pytorchviz/blob/master/torchviz/dot.py#L116)

**Comment by albanD** [comment]
cc @soulitzer
