### ISSUE TITLE
torchviz module not found

### ISSUE THREAD

**Issue by egmaminta** [szagoruyko/pytorchviz#72]
Good day! I just discovered this handy package. I followed the instructions (installed thru pip install torchviz, etc.) but when I run my code, it produces an error saying that torchviz module is not found. I was hoping you could enlighten me on this. Thank you!

**Comment by albanD** [comment]
Hi,

This usually happens because you installed with pip for a different version of python compared to the one where you try to run the code.
You can avoid this by doing:
```bash
python -m pip install torchviz
python
>>> import torchviz # That one should work fine
```

**Comment by egmaminta** [comment]
I see. Thank you!
